#include <iostream>
#include <cstring>
#include <string.h>
using namespace std;



int main(){

     // string s="abcd";
     string s1;  //string are call by value by default
  // cin>>s1;  //till space or enter
  getline(cin,s1);  //include space as well
   cout << s1 << endl;

      //string  s2="ef";
      //string s3=s1+s2;  //it is not defined for character array
      //string s=s1.substr(1,2);
     // cout << s << endl;
     //int n=s1.length(); //length of string
    // cout << n << endl;
      //cout << s3 << endl;

     //s[0]='d';
     //cout << s[0] << endl;
    // string s1=""; //it makes an empty string

    /* for(int i=0;i<4;i++ ){
        char c;
        cin>>c;
        s1+=c;
     }
     */
    // cout << s1 << endl;





}


