#include <iostream>   //header file has cout defined
using namespace std;   //use standard namespace

//: means comments ie.those section of your code that complier ignores
/*
mutliple line comment
*/



int main(){ //starting point of your code

   // int p,r,t;
    //int p;
    //int r;
    //int t;
   // cin>>p>>r>>t;

    int x;
    x=0;
    //cout << 5/x << endl;

  //  float si=(p*r*t)/100.0;   //gives float
    //float si=(p*r*t)/100;   gives int
   // cout << si << endl;

    //exit statement - program ends here
    return 0;  //0 means program excuetes successfully
}



