#include <iostream>   //header file has cout defined
using namespace std;   //use standard namespace

//: means comments ie.those section of your code that complier ignores
/*
mutliple line comment
*/



int main(){ //starting point of your code
   // cout << "Hello World";  //cout is used to print something on console

    int x;
    cin>>x;       //cin:take input from user
    cout << x;

    //exit statement - program ends here
    return 0;  //0 means program excuetes successfully
}

